### ISSUE TITLE
esse projeto está ativo?

### ISSUE THREAD

**Issue by ghost** [matheus-vieira/solicitar#2]
Olá a todos.

esse projeto está ativo?

*gostaria de contribuir com algumas ideias*

**Comment by matheus-vieira** [comment]
Opa, se quiser contribuir fique a vontade.

Na real acabou sendo mais uma ideia do que um projeto

**Comment by matheus-vieira** [comment]
Que tipo de ideias tens?

**Comment by matheus-vieira** [comment]
Parece uma ideia bacana, mas precisa realmente integrar com uma biblioteca de pdf?

Acho que é possível fazer o JS ler o json gerado e criar uma página para ser impressa.

Que acha?

**Comment by matheus-vieira** [comment]
Além disso teria que ter uma forma de armazenar os dados solicitados.

Hoje esses dados apenas pegam as informações e a encaminham por e-mail/WhatsApp.

Como é utilizado coisas exclusivamente estáticas, podemos realizar uma chamada um um endpoint (alguma função em uma nuvem) para realizar o armazenamento.

Tendo isso podemos ter a geração do pdf

**Comment by matheus-vieira** [comment]
A parte de ser serverless muito me agrada.

Não conheço esse baço de dados, mas parece ser uma boa forma de fazer o que se necessita.

Lembrando esse projeto não está em "produção" mas se essa implementação for realmente boa, pode ser utilizado em outros casos de usos

**Comment by matheus-vieira** [comment]
Fiz umas alterações no projeto:


* adicionei a gem "webrick" no Gemfile to avoid erros on build
* o json de estabelecimentos é um array de verdade agora

**Comment by matheus-vieira** [comment]
As alterações já podem ser visualizadas:

[estabelecimentos.json](https://matheus-vieira.github.io/solicitar/assets/json/estabelecimentos.json)

A página que utiliza esse json continua funcionando [Selecionar Estabelecimento.](https://matheus-vieira.github.io/solicitar/estabelecimento/)

**Comment by matheus-vieira** [comment]
O texto que aparece inicialmente efetuei uns ajustes:

 Devido à pandemia causado pelo coronavírus espalhando o covid-19 mundo afora, profissionais de saúde e governantes recomendam que as pessoas fiquem em quarentena e que se mantenha um distanciamento social. Porém, ainda precisamos de itens, serviços, e em alguns casos, doações. Com a necessidade informada acima foi disponibilizado esse site para conectar pessoas e estabelecimentos virtualmente. Precisa comprar pão, solicite a uma padaria ou mercado. Você dono de estabelecimento, utilize esse site para receber encomendas. Dessa forma evitamos superfaturamentos de plataformas de entregas. E ainda ajudamos os pequenos comerciantes. Portanto, fique em casa!

**Comment by matheus-vieira** [comment]
Se quiser, no [meu site](https://matheus-vieira.github.io/) tem outras formas de conato comigo.

Talvez seja melhor do que aqui.

**Comment by matheus-vieira** [comment]
eu vi, inclusive o comentário anterior foi sobre esse site novo

**Comment by matheus-vieira** [comment]
Ficou bacana, bootsrap clássico!

Se for alterar layout recomento alterar tudo, somente o “miolo” da página vai ficar estranho, digo isso por que o cabeçalho está com outro estilo.

Na página inicial eu não sei ainda o que o usuário do sistema quer, se é solicitar ou cadastrar um estabelecimento.

Não sei qual seria o teu objetivo nesse início.

**Comment by matheus-vieira** [comment]
Eu também acredito que o usuário precisa de micro decisões.

No [meu exemplo](https://matheus-vieira.github.io/solicitar/) eu alteraria o texto "Comece aqui" por "Solicite Aqui", por questões de claridade, já o Cadastre um estabelecimento acho que está claro o suficiente.

Aliás vou altera isso já e colocar os botões para cima também.

**Comment by matheus-vieira** [comment]
Atualizei a minha versão com os links duplicados, podes ver [aqui](https://matheus-vieira.github.io/solicitar/).

**Comment by matheus-vieira** [comment]
> então... minha ideia é tipo adicionar uma camada de passo a passo, e depois do cadastro o usuário ter uma cópia local dos dados de cadastro, uma cópia pública no orbit-db e uma cópia externa no google drive/dropbox - caso o usuário tenha a conta num desses serviços.

Será que precisamos disso? E se utilizar um local-storage para realizar esse armazenamento apenas local, sem dependências externas para o usuário.?

> o que acha da ideia de oferecer suporte múltiplo ao cadastro?

o que seria essa ideia de "múltiplo cadastro"

**Comment by matheus-vieira** [comment]
Hoje já uso o local storage para fazer alguns armazenamentos.

Pode ser que seja interessante ter no local storage os dados do cara para ele não ficar inserindo toda vez.

No momento que o usuário solicitar, verifica se tem informações no local storage,
* se tiver vai direto para a seleção do estabelecimento
* caso contrário solicita os dados
  * tem que ter uma informação dizendo que os dados são salvos localmente no navegador e será somente compartilhado com o estabelecimento selecionado

**Comment by matheus-vieira** [comment]
> o que você pensa da ideia de maior auditabilidade? de uma maior verificação dos dados de cadastro?

Na real não havia pensado sobre isso na época.

A ideia era basicamente agilizar a solicitação de itens em supermercado.
Por mais que foi solicitado a quarentena, e toda a ideia de ficar em casa, ainda precisávamos ir ao mercado comprar coisas como pão, leite, carne, etc.

**Comment by codehangen** [comment]
Oi matheus-vieira.

> Na real não havia pensado sobre isso na época.

entendo.

> A ideia era basicamente agilizar a solicitação de itens em supermercado.
> Por mais que foi solicitado a quarentena, e toda a ideia de ficar em casa, ainda precisávamos ir ao mercado comprar coisas como pão, leite, carne, etc.

Então pensei em algo assim:

![image](https://user-images.githubusercontent.com/111701513/216743440-4419c5d6-2a6a-4611-a46c-97df7992d071.png)

**Comment by matheus-vieira** [comment]
Gostei da ideia do fluxo, faz total sentido.

Mas o dado salvo externamente deve ser configurado para não ser armazenado por X tempo, sendo um tempo curto como dias.

Além de tudo estar como plano "de graça" e avisar antes de fazer um pagamento.
